### PR TITLE
EM-27 Allow Synchronous events

### LINKED ISSUE #27: Allow synchronous events
Currently, incoming events are all handled asynchronously through the event queue. When the event is received the EM will return a 200 code to the caller, signaling that the event has been received and queued correctly.

However, there may be some cases in which the caller wants to know which was the result of processing an event. This is currently something that is hard to do since the application would need to signal the caller asynchronously after the event is processed. 

A better approach would be to allow some events to be processed synchronously. That way this would work is that when the EM gets an event the following will happen:

1. it will check whether it is sync or not
1. if it is NOT sync then it will enqueue the event in the EventQueue and proceed normally
1. if on the other hand, the event is sync, then we will process the event immediately by obtaining the subscriptions of said event and triggering the `SendEvent` method. 

Note that the response of the invocation will need to be marshaled into a valid HTTP response somehow. The `SendEvent` method is already in charge of telling us which is the status code of the response by checking whether the processing of the event threw an exception or not. What we need to modify is the `SerializedString` variable in `SendEvent` so that it contains the serialized result of invoking the line `callback.Invoke(_event);`. 

Another change that should be made is that now callbacks must return a string (which should be the serialized response). Another option is for callbacks to return an `object` and we make `SendEvent` do something like `JsonConvert.SerializeObject` to convert the said object response to JSON. 

## Changes to appsettings

We should also add a new property to the event subscription objects in the appsettings file which allows the user to specify whether a subscription should be handled synchronously or asynchronously. If not specified then the subscription will be handled asynchronously. A good keyword for this could be `Synchronous`. For example:

```json
     "Subscriptions": [
       {
         "EventName": "my_custom_event_name",
         "Subscribers": [
           {
             "Name": "httpbin",  // event will be handled asynchronously since that is the default (synchronous=false)
             "Method": "POST",
             "Endpoint": "/post"
           },
           {
             "Name": "somesubscriber",
             "Method": "POST",
             "Endpoint": "/somenedpoint",
             "Synchronous": true    // event will be handled synchronously for this subscription
           },
         ]
       }
     ]
```

### PR DESCRIPTION
**Pull request by ssanabriacec**
Resolves #27 

Restrict to only one Synchronous Register

Call Synchronous only if Payload has the boolean

- Synchronous also comes from the incomming payload.

Restoring to execute all async first then sync

- We execute first all the Async calls
- We execute last the Sync call to not interrupt the Async calls
- We return the Sync response payload to the EM endpoint back to the caller

Callback return response

### CODE REVIEW

File: BusinessLogic/Entities/EventDispatcher.cs [hunk 1]
```diff
@@ -41,6 +42,29 @@ private EventDispatcher()
         public void Register(Subscription subscription)
         {
             Log.Debug("EventDispatcher.Register");
+
+
```
Comment (tupini07) [inline BusinessLogic/Entities/EventDispatcher.cs]: Let's add some documentation here to ensure that it is clear what is happening

```suggestion
            // If there is already a synchronous subscription then raise an exception
```

File: BusinessLogic/Entities/EventDispatcher.cs [hunk 2]
```diff
@@ -119,31 +146,64 @@ public void SimpleDispatch(string eventName, string eventPayload, Dictionary<str
...
             if (eventSubscriptions.TryGetValue(e.Name, out subscriptions))
             {
                 Log.Debug($"EventDispatcher.Dispatch: Found subscriptions to event '{e.Name}', enqueuing items");
-                foreach (Subscription subscription in subscriptions)
+
+                foreach (Subscription subscription in subscriptions.Where(x => !x.Synchronous))
                 {
-                    Log.Debug($"EventDispatcher.Dispatch: Enqueuing item for subscriber '{subscription.Subscriber.Name}', for event '{e.Name}'");
-                    QueueItem queueItem = new QueueItem()
+                    if (!subscription.Synchronous)
```
Comment (tupini07) [inline BusinessLogic/Entities/EventDispatcher.cs]: The `if` check above is not necessary because we're already **only** iterating through the subscriptions where `!x.Syncrhonous`

File: BusinessLogic/Entities/EventDispatcher.cs [hunk 3]
```diff
@@ -119,31 +146,64 @@ public void SimpleDispatch(string eventName, string eventPayload, Dictionary<str
...
+                // move to last because the return will break the other Queue items
+                Subscription synchronousSubscription = subscriptions.FirstOrDefault(s => s.Synchronous);
 
-                    queue.Add(queueItem);
+                if (synchronousSubscription != null)
+                {
+                    Log.Debug($"EventDispatcher.Dispatch: Executing Synchronous call for Event: '{e.Name}'");
+                    return synchronousSubscription.SendEvent(e).Result;
                 }
+
```
Comment (tupini07) [inline BusinessLogic/Entities/EventDispatcher.cs]: Add a comment:

```suggestion
                // if there is no synchronous event then just return an empty response with 200 status code
```

File: EventManager.csproj [hunk 4]
```diff
@@ -4,7 +4,7 @@
     <TargetFrameworks>netstandard2.0;</TargetFrameworks>
     <RootNamespace>EventManager</RootNamespace>
     <PackageId>Cecropia.Utilities.EventManager</PackageId>
-    <Version>1.2.0</Version>
+    <Version>2.0</Version>
```
Comment (tupini07) [inline EventManager.csproj]: Please add a patch version so that we respect semantic versioning:

```suggestion
    <Version>2.0.0</Version>
```

File: BusinessLogic/Entities/Subscription.cs [hunk 5]
```diff
@@ -99,7 +100,13 @@ public async Task<HttpResponseMessage> SendEvent(Event _event)
                 {
                     foreach (var callback in CallBacks)
                     {
+                        if (this.Synchronous)
```
Comment (tupini07) [inline BusinessLogic/Entities/Subscription.cs:105]: Add a comment above:

```suggestion
                        // if the subscription is synchronous then it should only have one callback so we're safe returning its response here
                        if (this.Synchronous)
```

File: Middleware/EventManagerMiddleware.cs [hunk 6]
```diff
@@ -100,12 +103,36 @@ public async Task InvokeAsync(HttpContext httpContext)
...
                     Payload = json["Payload"].ToString(Formatting.None),
-                    ExtraParams = json["ExtraParams"].ToObject<JObject>(),
+                    ExtraParams = json["ExtraParams"].ToObject<JObject>()
                 };
 
-                EventDispatcher.Dispatch(e);
+                HttpResponseMessage httpResponseMessage = EventDispatcher.Dispatch(e);
 
-                httpContext.Response.StatusCode = 200;
+                if (httpResponseMessage == null)
```
Comment (tupini07) [inline Middleware/EventManagerMiddleware.cs:113]: Add comment

```suggestion
                // if the response message is `null` then it means the event had no synchronous callbacks and that all
                // async callbacks have been queued for execution, see we can return 200 status
                if (httpResponseMessage == null)
```

**Review by tupini07 — CHANGES_REQUESTED** [review]

File: BusinessLogic/Entities/EventDispatcher.cs (hunk 2 above)
Comment (ssanabriacec) [reply BusinessLogic/Entities/EventDispatcher.cs]: fixed

File: EventManager.csproj (hunk 4 above)
Comment (ssanabriacec) [reply EventManager.csproj]: fixed too

File: Middleware/EventManagerMiddleware.cs (hunk 6 above)
Comment (ssanabriacec) [reply Middleware/EventManagerMiddleware.cs:113]: fixed too

File: BusinessLogic/Entities/Subscription.cs (hunk 5 above)
Comment (ssanabriacec) [reply BusinessLogic/Entities/Subscription.cs:105]: fixed too

File: BusinessLogic/Entities/EventDispatcher.cs (hunk 3 above)
Comment (ssanabriacec) [reply BusinessLogic/Entities/EventDispatcher.cs]: fixed too

File: BusinessLogic/Entities/EventDispatcher.cs (hunk 1 above)
Comment (ssanabriacec) [reply BusinessLogic/Entities/EventDispatcher.cs]: fixed too

**Review by tupini07 — APPROVED** [review]
